### Метод для авторизации
POST http://localhost:8080/api/v1/auth/login/
Content-Type: application/json

{
  "email": "annten1@mail.com",
  "password": "SecurePass456!"
}

> {%
    client.global.set("access_token", response.body.access_token);
%}

### Метод для получения данных о профиле
GET http://localhost:8080/api/v1/profile/
Authorization: Bearer {{access_token}}

### Идентификатор профиля другого пользователя
@foreignProfileId=

### Метод для получения профиля другого пользователя по ID
GET http://localhost:8080/api/v1/profile/{{foreignProfileId}}/
Authorization: Bearer {{access_token}}

### Метод для обновления данных профиля
PATCH http://localhost:8080/api/v1/profile/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "contactData": {
    "telegramLink": "user@example.com",
    "whatsappLink": "+1234567890",
    "phoneNumber": "123 Main Street, City, Country"
  },
  "individual": {
    "fullName": "Micha Иванов",
    "passportNumber": "1235 567890",
    "issuedBy": "УФМС России по г. Москве",
    "issueDate": "2020-01-15",
    "departmentCode": "770-001",
    "registrationAddress": "г. Москва, ул. Ленина, д. 10"
  }
}

###
#{
#  "contactData": {
#    "telegramLink": "user@ example.com",
#    "whatsappLink": "+1234567890",
#    "phoneNumber": "123 Main Street, City, Country"
#  },
#  "company": {
#    "name": "Example Corp",
#    "inn": "1234567890",
#    "ogrn": "1122334455667",
#    "bic": "044525225"
#  }
}