@reviewUrl=http://localhost:8080/api/v1/reviews

### Метод для авторизации
POST http://localhost:8080/api/v1/auth/login/
Content-Type: application/json

{
  "email": "annten1@mail.com",
  "password": "SecurePass456!"
}

> {%
    client.global.set("access_token", response.body.access_token);
%}

### Идентификатор профиля, которому выставляется отзыв (комментируемый профиль)
@profileId=8580715a-c7b0-41d4-9112-0deae1ac0e7f

### Метод для создания отзыва
POST {{reviewUrl}}/profile/{{profileId}}/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "comment": "Неплохо справился с работой. Можно будет повторить контракт",
  "rating": 4
}

### Идентификатор отзыва
@reviewId=06397646-5d7d-438d-a0bb-a13e0e116cab

### Метода для обновления данных отзыва
PATCH {{reviewUrl}}/{{reviewId}}/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "comment": "Отличная работа супер!",
  "rating": 3
}

### Метод для получения данных по отзыву
GET {{reviewUrl}}/{{reviewId}}/
Authorization: Bearer {{access_token}}
Accept: application/json

### Метод для получения списка отзывов профиля и отзывов текущего профиля над комментируемым [MINE, ALL]
GET {{reviewUrl}}/profile/{{profileId}}/?reviewType=ALL&pageNumber=1&pageSize=5
Authorization: Bearer {{access_token}}
Accept: application/json

### Метод для получения списка отзывов авторизованного пользователя (текущего пользователя)
GET {{reviewUrl}}/mine/?pageNumber=1&pageSize=5
Authorization: Bearer {{access_token}}
Accept: application/json

### Метод для удаления отзыва по id
DELETE {{reviewUrl}}/{{reviewId}}/
Authorization: Bearer {{access_token}}